version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk    
    - image: appiriodevops/ap-microservice-base:0.0.1
    steps:
    - checkout    
    # This is based on your 1.0 configuration file or project settings
    - run: sudo apt install jq
    - run: sudo apt install awscli
    - run: docker login  -u $DOCKER_USER -p $DOCKER_PASSWD
    - setup_remote_docker     
    # The following line was run implicitly in your 1.0 builds based on what CircleCI inferred about the structure of your project. In 2.0 you need to be explicit about which commands should be run. In some cases you can discard inferred commands if they are not relevant to your project.
    - run: mvn dependency:go-offline || true
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.m2
    - run: mvn clean compile package
    - deploy:
        command: ./ecs_deploy.sh DEV
