version: 2
java_env: &java_env
  docker:
    - image: circleci/openjdk:8-jdk

python_env: &python_env
  docker:
    - image: circleci/python:2.7-stretch-browsers

install_awscli: &install_awscli
  name: "Install awscli"
  command: |
    sudo pip install awscli awsebcli --upgrade
    aws --version
    eb --version
  
deploy_steps: &deploy_steps
  - checkout
  - attach_workspace:
      at: .
  - run: *install_awscli
  - run: sudo apt-get update && sudo apt-get install -y jq
  - setup_remote_docker
  - run: .deploy/ecs_deploy.sh $DEPLOY_ENV

jobs:
  build:
    <<: *java_env
    steps:
      - checkout
      - run: mvn clean compile package
      - persist_to_workspace:
          root: .
          paths:
            - ./target

  deploy_prod:
    <<: *python_env
    environment:
      DEPLOY_ENV: "PROD"
    steps: *deploy_steps

  deploy_dev:
    <<: *python_env
    environment:
      DEPLOY_ENV: "DEV"
    steps: *deploy_steps
      

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_dev:
          filters:
            branches:
              only: dev
          requires:
            - build
      - deploy_prod:
          filters:
            branches:
              only: master
          requires:
            - build